function rho_reduced = calculateReducedDensityMatrix(state_vector, qubits_to_trace_out)
% Function to calculate the reduced density matrix of an n-qubit state
% by tracing out a specified set of m qubits.

% Input:
%   state_vector: A column vector representing the pure quantum state.
%                 Its length must be a power of 2 (2^n).
%   qubits_to_trace_out: A row vector of unique integer indices (1 to n)
%                        of the qubits to trace out. These indices refer
%                        to the position of the qubit in the state vector's
%                        computational basis representation (e.g., for |q1 q2 q3>,
%                        q1 is index 1, q2 is index 2, q3 is index 3).

% Output:
%   rho_reduced: The calculated reduced density matrix for the remaining qubits.
%   generated by Gemini on 28.07.2025

    % --- Input Validation ---
    % Determine the total number of qubits (n) from the state vector's length.
    n_total_qubits = log2(length(state_vector));
    if n_total_qubits ~= floor(n_total_qubits)
        error('Input state_vector length must be a power of 2.');
    end

    % Ensure the state_vector is a column vector.
    if ~iscolumn(state_vector)
        error('Input state_vector must be a column vector.');
    end

    % Get the number of qubits to be traced out (m).
    m_qubits_to_trace = length(qubits_to_trace_out);

    % Check if m is less than n.
    if m_qubits_to_trace >= n_total_qubits
        error('Number of qubits to trace out (m) must be less than total number of qubits (n).');
    end

    % Check if qubit indices are valid (between 1 and n).
    if any(qubits_to_trace_out < 1) || any(qubits_to_trace_out > n_total_qubits)
        error('Qubit indices to trace out must be between 1 and n (total qubits).');
    end

    % Check for unique qubit indices to trace out.
    if length(unique(qubits_to_trace_out)) ~= m_qubits_to_trace
        error('Qubit indices to trace out must be unique.');
    end

    % --- 1. Form the full density matrix ---
    % For a pure state |psi>, the density matrix rho = |psi><psi|.
    rho_full = state_vector * state_vector';

    % --- 2. Reshape the full density matrix into a 2n-dimensional tensor ---
    % This step is crucial for performing the partial trace efficiently.
    % The dimensions are ordered as: (Q1_ket, Q2_ket, ..., Qn_ket, Q1_bra, Q2_bra, ..., Qn_bra).
    % Each dimension has size 2.
    tensor_dims = 2 * ones(1, 2 * n_total_qubits);
    rho_tensor = reshape(rho_full, tensor_dims);

    % --- 3. Identify dimensions for keeping and tracing ---
    % Create a list of all qubit indices.
    all_qubit_indices = 1:n_total_qubits;
    % Determine which qubits are to be kept.
    kept_qubit_indices = setdiff(all_qubit_indices, qubits_to_trace_out);

    % Define the permutation order for the tensor dimensions.
    % We want to group the 'kept' dimensions first, then the 'traced' dimensions.
    % This applies to both the ket and bra parts of the tensor.
    perm_order_ket = [kept_qubit_indices, qubits_to_trace_out];
    perm_order_bra = n_total_qubits + perm_order_ket; % Corresponding bra dimensions (shifted by n_total_qubits)

    % Combine the ket and bra permutation orders.
    full_perm_order = [perm_order_ket, perm_order_bra];
    
    % Permute the dimensions of the tensor according to the defined order.
    rho_permuted = permute(rho_tensor, full_perm_order);

    % --- 4. Reshape for block-trace operation ---
    % Calculate the number of qubits that will remain and those being traced.
    num_kept_qubits = length(kept_qubit_indices);
    num_traced_qubits = length(qubits_to_trace_out);

    % Calculate the size of the Hilbert space for the kept and traced parts.
    size_kept = 2^num_kept_qubits;
    size_traced = 2^num_traced_qubits;

    % Reshape the permuted tensor into a 4-block structure:
    % (kept_ket_basis_idx, traced_ket_basis_idx, kept_bra_basis_idx, traced_bra_basis_idx)
    % This makes it easy to perform the partial trace by summing over the 'traced' blocks.
    rho_block = reshape(rho_permuted, [size_kept, size_traced, size_kept, size_traced]);

    % --- 5. Perform the partial trace ---
    % Initialize the reduced density matrix. Its size will be size_kept x size_kept.
    rho_reduced = zeros(size_kept, size_kept);

    % Iterate through the basis states of the kept subsystem (both ket and bra indices).
    for i = 1:size_kept % Index for the kept-ket part
        for j = 1:size_kept % Index for the kept-bra part
            % Extract the relevant 2D sub-block. This sub-block represents the
            % correlation between the 'traced' qubits for a given kept-ket and kept-bra state.
            % 'squeeze' removes any singleton dimensions that might result if size_traced is 1.
            sub_block = squeeze(rho_block(i, :, j, :));
            
            % The partial trace is equivalent to taking the trace of this sub-block.
            % This sums over the diagonal elements of the traced-out qubits.
            rho_reduced(i,j) = trace(sub_block);
        end
    end

end

%{
% --- Example Usage ---

% Example 1: Separable State (from previous discussion)
% State: |psi> = (|000> + |101>) / sqrt(2)
% This state is separable with respect to partition A=(Q1Q3), B=(Q2).
% We expect rho_B (for Q2) to be |0><0|, and rho_A (for Q1Q3) to be pure.

n_qubits_ex1 = 3;
state_vector_ex1 = zeros(2^n_qubits_ex1, 1);
% In computational basis: |000> corresponds to index 1 (binary 000)
% |101> corresponds to index 6 (binary 101)
state_vector_ex1(bin2dec('000') + 1) = 1/sqrt(2); % |000>
state_vector_ex1(bin2dec('101') + 1) = 1/sqrt(2); % |101>

fprintf('--- Example 1: Separable State (|000> + |101>)/sqrt(2) ---\n');
fprintf('Original State Vector:\n');
disp(state_vector_ex1');

% Calculate rho_B (reduced density matrix for Q2) by tracing out Q1 and Q3.
qubits_to_trace_out_ex1_B = [1, 3]; % Indices of qubits to trace out (Q1 and Q3)
rho_B_reduced = calculateReducedDensityMatrix(state_vector_ex1, qubits_to_trace_out_ex1_B);
fprintf('Reduced Density Matrix for Q2 (rho_B):\n');
disp(rho_B_reduced);

% Expected rho_B: [[1, 0], [0, 0]] (representing |0><0| for Q2)
% Check purity: trace(rho_B^2). For a pure state, purity should be 1.
purity_B = trace(rho_B_reduced * rho_B_reduced);
fprintf('Purity of rho_B: %f\n', purity_B); % Should be 1.000000

% Calculate rho_A (reduced density matrix for Q1Q3) by tracing out Q2.
qubits_to_trace_out_ex1_A = 2; % Index of qubit to trace out (Q2)
rho_A_reduced = calculateReducedDensityMatrix(state_vector_ex1, qubits_to_trace_out_ex1_A);
fprintf('Reduced Density Matrix for Q1Q3 (rho_A):\n');
disp(rho_A_reduced);

% Expected rho_A: 0.5 * [[1,0,0,1],[0,0,0,0],[0,0,0,0],[1,0,0,1]] (representing (|00>+|11>)(<00|+<11|)/2)
% Check purity: trace(rho_A^2). For a pure state, purity should be 1.
purity_A = trace(rho_A_reduced * rho_A_reduced);
fprintf('Purity of rho_A: %f\n', purity_A); % Should be 1.000000

fprintf('\n');

% Example 2: Entangled State (Bell state |phi+>)
% State: |phi+> = (|00> + |11>) / sqrt(2)
% This state is entangled for any partition into single qubits.
% We expect rho_A and rho_B to be maximally mixed (purity 0.5 for a qubit).

n_qubits_ex2 = 2;
state_vector_ex2 = zeros(2^n_qubits_ex2, 1);
state_vector_ex2(bin2dec('00') + 1) = 1/sqrt(2); % |00>
state_vector_ex2(bin2dec('11') + 1) = 1/sqrt(2); % |11>

fprintf('--- Example 2: Entangled State (|00> + |11>)/sqrt(2) ---\n');
fprintf('Original State Vector:\n');
disp(state_vector_ex2');

% Calculate rho_B (reduced density matrix for Q2) by tracing out Q1.
qubits_to_trace_out_ex2_B = 1; % Trace out the 1st qubit (Q1)
rho_B_reduced_ex2 = calculateReducedDensityMatrix(state_vector_ex2, qubits_to_trace_out_ex2_B);
fprintf('Reduced Density Matrix for Q2 (rho_B):\n');
disp(rho_B_reduced_ex2);

% Expected rho_B: [[0.5, 0], [0, 0.5]] (representing I/2 for Q2)
% Check purity: trace(rho_B^2). For a maximally mixed qubit, purity is 0.5.
purity_B_ex2 = trace(rho_B_reduced_ex2 * rho_B_reduced_ex2);
fprintf('Purity of rho_B: %f\n', purity_B_ex2); % Should be 0.500000

% Calculate rho_A (reduced density matrix for Q1) by tracing out Q2.
qubits_to_trace_out_ex2_A = 2; % Trace out the 2nd qubit (Q2)
rho_A_reduced_ex2 = calculateReducedDensityMatrix(state_vector_ex2, qubits_to_trace_out_ex2_A);
fprintf('Reduced Density Matrix for Q1 (rho_A):\n');
disp(rho_A_reduced_ex2);

% Expected rho_A: [[0.5, 0], [0, 0.5]] (representing I/2 for Q1)
purity_A_ex2 = trace(rho_A_reduced_ex2 * rho_A_reduced_ex2);
fprintf('Purity of rho_A: %f\n', purity_A_ex2); % Should be 0.500000
%}
